#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_PMS.Db
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class AnonDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public AnonDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnonDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnonDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnonDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AnonWaitingRoom> AnonWaitingRooms
		{
			get
			{
				return this.GetTable<AnonWaitingRoom>();
			}
		}
		
		public System.Data.Linq.Table<AnonPatient> AnonPatients
		{
			get
			{
				return this.GetTable<AnonPatient>();
			}
		}
		
		public System.Data.Linq.Table<AnonClaimantInvoice> AnonClaimantInvoices
		{
			get
			{
				return this.GetTable<AnonClaimantInvoice>();
			}
		}
		
		public System.Data.Linq.Table<AnonUnPaidInvoice> AnonUnPaidInvoices
		{
			get
			{
				return this.GetTable<AnonUnPaidInvoice>();
			}
		}
		
		public System.Data.Linq.Table<AnonUnCancelledInvoices> AnonUnCancelledInvoices
		{
			get
			{
				return this.GetTable<AnonUnCancelledInvoices>();
			}
		}
		
		public System.Data.Linq.Table<AnonPhysioAppointments> AnonPhysioAppointments
		{
			get
			{
				return this.GetTable<AnonPhysioAppointments>();
			}
		}
		
		public System.Data.Linq.Table<AnonInvoiceLines> AnonInvoiceLines
		{
			get
			{
				return this.GetTable<AnonInvoiceLines>();
			}
		}
		
		public System.Data.Linq.Table<AnonAppointments> AnonAppointments
		{
			get
			{
				return this.GetTable<AnonAppointments>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class AnonWaitingRoom
	{
		
		private int _ID;
		
		private string _Name;
		
		private string _Physio;
		
		private string _Rate;
		
		private string _Start;
		
		private string _End;
		
		private int _AppointmentID;
		
		private System.Nullable<System.DateTime> _DOB;
		
		public AnonWaitingRoom()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Physio", CanBeNull=false)]
		public string Physio
		{
			get
			{
				return this._Physio;
			}
			set
			{
				if ((this._Physio != value))
				{
					this._Physio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", CanBeNull=false)]
		public string Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this._Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start", CanBeNull=false)]
		public string Start
		{
			get
			{
				return this._Start;
			}
			set
			{
				if ((this._Start != value))
				{
					this._Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End", CanBeNull=false)]
		public string End
		{
			get
			{
				return this._End;
			}
			set
			{
				if ((this._End != value))
				{
					this._End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppointmentID")]
		public int AppointmentID
		{
			get
			{
				return this._AppointmentID;
			}
			set
			{
				if ((this._AppointmentID != value))
				{
					this._AppointmentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this._DOB = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class AnonPatient
	{
		
		private System.Nullable<int> _PatientID;
		
		private System.Nullable<System.DateTime> _BirthDate;
		
		private string _Sex;
		
		private string _Comments;
		
		private string _PhysioID;
		
		private string _DVANumber;
		
		private System.Nullable<bool> _PatientInActive;
		
		private string _Title;
		
		private string _Address;
		
		private string _Suburb;
		
		private string _State;
		
		private string _PostCode;
		
		private string _HomePhone;
		
		private string _BusPhone;
		
		private string _Fax;
		
		private string _Mobile;
		
		private string _Email;
		
		private string _Name;
		
		private string _FirstName;
		
		private string _LastName;
		
		private System.Nullable<bool> _Family;
		
		private System.Nullable<bool> _Friend;
		
		private System.Nullable<bool> _FrontSign;
		
		private System.Nullable<bool> _YellowPages;
		
		private System.Nullable<bool> _Internet;
		
		private System.Nullable<bool> _HealthFund;
		
		private System.Nullable<bool> _HealthProfessional;
		
		private string _Other;
		
		private System.Nullable<int> _RefDoctor;
		
		private System.Nullable<bool> _CardiacPacemaker;
		
		private System.Nullable<bool> _LossOfWeight;
		
		private System.Nullable<bool> _HeartCondition;
		
		private System.Nullable<bool> _Dizziness;
		
		private System.Nullable<bool> _ArtificialJoint;
		
		private System.Nullable<bool> _Epilepsy;
		
		private System.Nullable<bool> _SurgeryInThePast3Months;
		
		private System.Nullable<bool> _Smoker;
		
		private System.Nullable<bool> _ReferredByDoc;
		
		public AnonPatient()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> PatientID
		{
			get
			{
				return this._PatientID;
			}
			set
			{
				if ((this._PatientID != value))
				{
					this._PatientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDate", DbType="Date", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this._BirthDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="NVarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this._Sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this._Comments = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysioID", DbType="NVarChar(3)", UpdateCheck=UpdateCheck.Never)]
		public string PhysioID
		{
			get
			{
				return this._PhysioID;
			}
			set
			{
				if ((this._PhysioID != value))
				{
					this._PhysioID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVANumber", DbType="NVarChar(14)", UpdateCheck=UpdateCheck.Never)]
		public string DVANumber
		{
			get
			{
				return this._DVANumber;
			}
			set
			{
				if ((this._DVANumber != value))
				{
					this._DVANumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientInActive", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> PatientInActive
		{
			get
			{
				return this._PatientInActive;
			}
			set
			{
				if ((this._PatientInActive != value))
				{
					this._PatientInActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suburb", CanBeNull=false)]
		public string Suburb
		{
			get
			{
				return this._Suburb;
			}
			set
			{
				if ((this._Suburb != value))
				{
					this._Suburb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostCode", CanBeNull=false)]
		public string PostCode
		{
			get
			{
				return this._PostCode;
			}
			set
			{
				if ((this._PostCode != value))
				{
					this._PostCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomePhone", CanBeNull=false)]
		public string HomePhone
		{
			get
			{
				return this._HomePhone;
			}
			set
			{
				if ((this._HomePhone != value))
				{
					this._HomePhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusPhone", CanBeNull=false)]
		public string BusPhone
		{
			get
			{
				return this._BusPhone;
			}
			set
			{
				if ((this._BusPhone != value))
				{
					this._BusPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", CanBeNull=false)]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", CanBeNull=false)]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Family", DbType="Bit")]
		public System.Nullable<bool> Family
		{
			get
			{
				return this._Family;
			}
			set
			{
				if ((this._Family != value))
				{
					this._Family = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Friend", DbType="Bit")]
		public System.Nullable<bool> Friend
		{
			get
			{
				return this._Friend;
			}
			set
			{
				if ((this._Friend != value))
				{
					this._Friend = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrontSign", DbType="Bit")]
		public System.Nullable<bool> FrontSign
		{
			get
			{
				return this._FrontSign;
			}
			set
			{
				if ((this._FrontSign != value))
				{
					this._FrontSign = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YellowPages", DbType="Bit")]
		public System.Nullable<bool> YellowPages
		{
			get
			{
				return this._YellowPages;
			}
			set
			{
				if ((this._YellowPages != value))
				{
					this._YellowPages = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Internet", DbType="Bit")]
		public System.Nullable<bool> Internet
		{
			get
			{
				return this._Internet;
			}
			set
			{
				if ((this._Internet != value))
				{
					this._Internet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HealthFund", DbType="Bit")]
		public System.Nullable<bool> HealthFund
		{
			get
			{
				return this._HealthFund;
			}
			set
			{
				if ((this._HealthFund != value))
				{
					this._HealthFund = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HealthProfessional", DbType="Bit")]
		public System.Nullable<bool> HealthProfessional
		{
			get
			{
				return this._HealthProfessional;
			}
			set
			{
				if ((this._HealthProfessional != value))
				{
					this._HealthProfessional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other", DbType="NVarChar(MAX)")]
		public string Other
		{
			get
			{
				return this._Other;
			}
			set
			{
				if ((this._Other != value))
				{
					this._Other = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefDoctor", DbType="Int")]
		public System.Nullable<int> RefDoctor
		{
			get
			{
				return this._RefDoctor;
			}
			set
			{
				if ((this._RefDoctor != value))
				{
					this._RefDoctor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardiacPacemaker", DbType="Bit")]
		public System.Nullable<bool> CardiacPacemaker
		{
			get
			{
				return this._CardiacPacemaker;
			}
			set
			{
				if ((this._CardiacPacemaker != value))
				{
					this._CardiacPacemaker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LossOfWeight", DbType="Bit")]
		public System.Nullable<bool> LossOfWeight
		{
			get
			{
				return this._LossOfWeight;
			}
			set
			{
				if ((this._LossOfWeight != value))
				{
					this._LossOfWeight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeartCondition", DbType="Bit")]
		public System.Nullable<bool> HeartCondition
		{
			get
			{
				return this._HeartCondition;
			}
			set
			{
				if ((this._HeartCondition != value))
				{
					this._HeartCondition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dizziness", DbType="Bit")]
		public System.Nullable<bool> Dizziness
		{
			get
			{
				return this._Dizziness;
			}
			set
			{
				if ((this._Dizziness != value))
				{
					this._Dizziness = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArtificialJoint", DbType="Bit")]
		public System.Nullable<bool> ArtificialJoint
		{
			get
			{
				return this._ArtificialJoint;
			}
			set
			{
				if ((this._ArtificialJoint != value))
				{
					this._ArtificialJoint = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Epilepsy", DbType="Bit")]
		public System.Nullable<bool> Epilepsy
		{
			get
			{
				return this._Epilepsy;
			}
			set
			{
				if ((this._Epilepsy != value))
				{
					this._Epilepsy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurgeryInThePast3Months", DbType="Bit")]
		public System.Nullable<bool> SurgeryInThePast3Months
		{
			get
			{
				return this._SurgeryInThePast3Months;
			}
			set
			{
				if ((this._SurgeryInThePast3Months != value))
				{
					this._SurgeryInThePast3Months = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Smoker", DbType="Bit")]
		public System.Nullable<bool> Smoker
		{
			get
			{
				return this._Smoker;
			}
			set
			{
				if ((this._Smoker != value))
				{
					this._Smoker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferredByDoc", DbType="Bit")]
		public System.Nullable<bool> ReferredByDoc
		{
			get
			{
				return this._ReferredByDoc;
			}
			set
			{
				if ((this._ReferredByDoc != value))
				{
					this._ReferredByDoc = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class AnonClaimantInvoice
	{
		
		private string _PhysioID;
		
		private System.Nullable<int> _InvoiceNo;
		
		private System.Nullable<System.DateTime> _TranDate;
		
		private string _Narrative;
		
		private System.Nullable<decimal> _TranAmount;
		
		private System.Nullable<decimal> _GST;
		
		private System.Nullable<bool> _InvoicePaid;
		
		public AnonClaimantInvoice()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysioID", DbType="NVarChar(3)")]
		public string PhysioID
		{
			get
			{
				return this._PhysioID;
			}
			set
			{
				if ((this._PhysioID != value))
				{
					this._PhysioID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNo", DbType="Int")]
		public System.Nullable<int> InvoiceNo
		{
			get
			{
				return this._InvoiceNo;
			}
			set
			{
				if ((this._InvoiceNo != value))
				{
					this._InvoiceNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TranDate", DbType="Date")]
		public System.Nullable<System.DateTime> TranDate
		{
			get
			{
				return this._TranDate;
			}
			set
			{
				if ((this._TranDate != value))
				{
					this._TranDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Narrative", DbType="NVarChar(50)")]
		public string Narrative
		{
			get
			{
				return this._Narrative;
			}
			set
			{
				if ((this._Narrative != value))
				{
					this._Narrative = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TranAmount", DbType="Money")]
		public System.Nullable<decimal> TranAmount
		{
			get
			{
				return this._TranAmount;
			}
			set
			{
				if ((this._TranAmount != value))
				{
					this._TranAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GST", DbType="Money")]
		public System.Nullable<decimal> GST
		{
			get
			{
				return this._GST;
			}
			set
			{
				if ((this._GST != value))
				{
					this._GST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoicePaid", DbType="Bit")]
		public System.Nullable<bool> InvoicePaid
		{
			get
			{
				return this._InvoicePaid;
			}
			set
			{
				if ((this._InvoicePaid != value))
				{
					this._InvoicePaid = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class AnonUnPaidInvoice
	{
		
		private int _InvoiceNo;
		
		private decimal _Balance;
		
		private decimal _ReceiptTotal;
		
		private decimal _InvoiceTotal;
		
		private System.DateTime _InvoiceDate;
		
		private decimal _ReceiptAmount;
		
		public AnonUnPaidInvoice()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNo")]
		public int InvoiceNo
		{
			get
			{
				return this._InvoiceNo;
			}
			set
			{
				if ((this._InvoiceNo != value))
				{
					this._InvoiceNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance")]
		public decimal Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptTotal")]
		public decimal ReceiptTotal
		{
			get
			{
				return this._ReceiptTotal;
			}
			set
			{
				if ((this._ReceiptTotal != value))
				{
					this._ReceiptTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceTotal")]
		public decimal InvoiceTotal
		{
			get
			{
				return this._InvoiceTotal;
			}
			set
			{
				if ((this._InvoiceTotal != value))
				{
					this._InvoiceTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate")]
		public System.DateTime InvoiceDate
		{
			get
			{
				return this._InvoiceDate;
			}
			set
			{
				if ((this._InvoiceDate != value))
				{
					this._InvoiceDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptAmount")]
		public decimal ReceiptAmount
		{
			get
			{
				return this._ReceiptAmount;
			}
			set
			{
				if ((this._ReceiptAmount != value))
				{
					this._ReceiptAmount = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class AnonUnCancelledInvoices
	{
		
		private int _InvoiceNo;
		
		private decimal _InvoiceAmount;
		
		private System.DateTime _InvoiceDate;
		
		private bool _InvoiceCancelled;
		
		public AnonUnCancelledInvoices()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNo")]
		public int InvoiceNo
		{
			get
			{
				return this._InvoiceNo;
			}
			set
			{
				if ((this._InvoiceNo != value))
				{
					this._InvoiceNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceAmount")]
		public decimal InvoiceAmount
		{
			get
			{
				return this._InvoiceAmount;
			}
			set
			{
				if ((this._InvoiceAmount != value))
				{
					this._InvoiceAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate")]
		public System.DateTime InvoiceDate
		{
			get
			{
				return this._InvoiceDate;
			}
			set
			{
				if ((this._InvoiceDate != value))
				{
					this._InvoiceDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceCancelled")]
		public bool InvoiceCancelled
		{
			get
			{
				return this._InvoiceCancelled;
			}
			set
			{
				if ((this._InvoiceCancelled != value))
				{
					this._InvoiceCancelled = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class AnonPhysioAppointments
	{
		
		private string _Name;
		
		private string _Physio;
		
		private string _Rate;
		
		private System.DateTime _Start;
		
		private System.DateTime _End;
		
		public AnonPhysioAppointments()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Physio", CanBeNull=false)]
		public string Physio
		{
			get
			{
				return this._Physio;
			}
			set
			{
				if ((this._Physio != value))
				{
					this._Physio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", CanBeNull=false)]
		public string Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this._Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start")]
		public System.DateTime startDate
		{
			get
			{
				return this._Start;
			}
			set
			{
				if ((this._Start != value))
				{
					this._Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End")]
		public System.DateTime endDate
		{
			get
			{
				return this._End;
			}
			set
			{
				if ((this._End != value))
				{
					this._End = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class AnonInvoiceLines
	{
		
		private System.Nullable<int> _PatientID;
		
		private System.Nullable<System.DateTime> _SessionDate;
		
		private string _RateID;
		
		private System.Nullable<decimal> _Fee;
		
		private string _ItemNo;
		
		private System.Nullable<decimal> _GST;
		
		private string _PatientName;
		
		public AnonInvoiceLines()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="Int")]
		public System.Nullable<int> PatientID
		{
			get
			{
				return this._PatientID;
			}
			set
			{
				if ((this._PatientID != value))
				{
					this._PatientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionDate", DbType="Date")]
		public System.Nullable<System.DateTime> SessionDate
		{
			get
			{
				return this._SessionDate;
			}
			set
			{
				if ((this._SessionDate != value))
				{
					this._SessionDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RateID", DbType="NVarChar(2)")]
		public string RateID
		{
			get
			{
				return this._RateID;
			}
			set
			{
				if ((this._RateID != value))
				{
					this._RateID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee", DbType="Money")]
		public System.Nullable<decimal> Fee
		{
			get
			{
				return this._Fee;
			}
			set
			{
				if ((this._Fee != value))
				{
					this._Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemNo", DbType="NVarChar(7)")]
		public string ItemNo
		{
			get
			{
				return this._ItemNo;
			}
			set
			{
				if ((this._ItemNo != value))
				{
					this._ItemNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GST", DbType="Money")]
		public System.Nullable<decimal> GST
		{
			get
			{
				return this._GST;
			}
			set
			{
				if ((this._GST != value))
				{
					this._GST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientName", CanBeNull=false)]
		public string PatientName
		{
			get
			{
				return this._PatientName;
			}
			set
			{
				if ((this._PatientName != value))
				{
					this._PatientName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class AnonAppointments
	{
		
		private int _ID;
		
		private string _Name;
		
		private string _Physio;
		
		private string _Rate;
		
		private string _Start;
		
		private string _End;
		
		private int _AppointmentID;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private System.DateTime _Date;
		
		public AnonAppointments()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Physio", CanBeNull=false)]
		public string Physio
		{
			get
			{
				return this._Physio;
			}
			set
			{
				if ((this._Physio != value))
				{
					this._Physio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", CanBeNull=false)]
		public string Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this._Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start", CanBeNull=false)]
		public string Start
		{
			get
			{
				return this._Start;
			}
			set
			{
				if ((this._Start != value))
				{
					this._Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End", CanBeNull=false)]
		public string End
		{
			get
			{
				return this._End;
			}
			set
			{
				if ((this._End != value))
				{
					this._End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppointmentID")]
		public int AppointmentID
		{
			get
			{
				return this._AppointmentID;
			}
			set
			{
				if ((this._AppointmentID != value))
				{
					this._AppointmentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this._DOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
